runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: server.main.app

- url: (.*)/
  static_files: client\1/index.html
  upload: app

- url: (.*)
  static_files: client\1
  upload: app
