runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /api/.*
  script: server.main.app

- url: /controll(/app/.*)
  static_files: client\1
  upload: app

- url: /controll(/assets/.*)
  static_files: client\1
  upload: app

- url: /controll/(.*)
  static_files: client/index.html
  upload: app

- url: /controll
  static_files: client/index.html
  upload: app

- url: (/.*)
  static_files: \1
  upload: app

