runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /api/.*
  script: server.main.app

- url: /controll(/app/.*)
  static_files: client\1
  upload: client/app/(.*)

- url: /controll(/assets/.*)
  static_files: client\1
  upload: client/assets/(.*)

- url: /controll/(.*)
  static_files: client/index.html
  upload: client/index.html

- url: /controll
  static_files: client/index.html
  upload: client/index.html

- url: /
  static_files: index.html
  upload: index.html

- url: (/.*)
  static_files: \1
  upload: index.html

